metadata:
  rows: 560426
  columns: 25
schema:
- name: game_id
  dtype: int32
- name: play_id
  dtype: int32
- name: player_to_predict
  dtype: object
- name: nfl_id
  dtype: int32
- name: frame_id
  dtype: int32
- name: play_direction
  dtype: object
- name: absolute_yardline_number
  dtype: int32
- name: player_name
  dtype: object
- name: player_height
  dtype: object
- name: player_weight
  dtype: int32
- name: player_birth_date
  dtype: object
- name: player_position
  dtype: object
- name: player_side
  dtype: object
- name: player_role
  dtype: object
- name: x
  dtype: float32
- name: y
  dtype: float32
- name: s
  dtype: float32
- name: a
  dtype: float32
- name: dir
  dtype: float32
- name: o
  dtype: float32
- name: num_frames_output
  dtype: int32
- name: ball_land_x
  dtype: float32
- name: ball_land_y
  dtype: float32
- name: target_x
  dtype: float32
- name: target_y
  dtype: float32
